# Generated by Django 4.2 on 2025-03-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=255)),
                ('description', models.TextField(help_text='Description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', help_text='Current status of the product.', max_length=10)),
                ('category', models.ForeignKey(help_text='Category of the product.', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
