# Generated by Django 4.2 on 2025-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_until',
            field=models.DateField(blank=True, help_text='Date until which the product is available.', null=True),
        ),
    ]
