# Generated by Django 4.2 on 2025-03-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the transaction.', max_length=10),
        ),
    ]
