# Generated by Django 4.2 on 2025-03-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_total_price_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
