# Generated by Django 4.2 on 2025-03-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_likes_product_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_transaction_order_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('face-to-face', 'Face-to-Face'), ('shipping', 'Shipping')], help_text='The chosen delivery method.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', help_text='The status of the return request.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(default=3, help_text='The user who sold the product.', on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(help_text='The user who purchased the product.', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='The reason for cancellation (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the transaction was created.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_serial',
            field=models.CharField(blank=True, help_text='Unique order serial number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='The time when the payment was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], help_text='The payment method used by the buyer.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(help_text='The product involved in the transaction.', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='The delivery address for the product.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The status of the transaction.', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The total price of the transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='The reference number provided by the payment gateway.', max_length=255, null=True),
        ),
    ]
