# Generated by Django 4.2 on 2025-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_location_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='return_rate',
            field=models.FloatField(default=0.0, help_text='Return rate percentage.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='transactions',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed transactions.'),
        ),
    ]
