# Generated by Django 4.2 on 2025-03-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmanageduser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='adminmanageduser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='adminmanageduser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminmanageduser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_managed_user', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminmanageduser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user is active (not banned).'),
        ),
    ]
