# Generated by Django 4.2 on 2025-03-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminmanageduser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminproductapproval',
            name='product',
        ),
        migrations.RemoveField(
            model_name='admintransactionstatus',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='AdminManagedUser',
        ),
        migrations.DeleteModel(
            name='AdminProductApproval',
        ),
        migrations.DeleteModel(
            name='AdminTransactionStatus',
        ),
    ]
