# Generated by Django 4.2 on 2025-03-19 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_transaction_delivery_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating given by the user (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Content of the review.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the review was created.')),
                ('likes', models.PositiveIntegerField(default=0, help_text='Number of likes for the review.')),
                ('transaction', models.ForeignKey(help_text='Transaction associated with this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transactions.transaction')),
                ('user', models.ForeignKey(help_text='User who wrote the review (buyer).', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('transaction', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image attached to the review.', upload_to='review_images/%Y/%m/%d/')),
                ('review', models.ForeignKey(help_text='Review associated with this image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
        ),
    ]
