# Generated by Django 4.2 on 2025-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the message was sent.')),
            ],
        ),
    ]
