# Generated by Django 4.2 on 2025-03-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the message has been read by the receiver.'),
        ),
    ]
