# Generated by Django 4.2 on 2025-03-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='product',
        ),
    ]
